const REACT_APP_INFURA_PROJECT_ID = process.env.REACT_APP_INFURA_PROJECT_ID;
const REACT_APP_INFURA_PROJECT_SECRET = process.env.REACT_APP_INFURA_PROJECT_SECRET;
const REACT_APP_INFURA_ENDPOINT_ETH2 = process.env.REACT_APP_INFURA_ENDPOINT_ETH2;

module.exports = {
  REACT_APP_INFURA_PROJECT_ID,
  REACT_APP_INFURA_PROJECT_SECRET,
  REACT_APP_INFURA_ENDPOINT_ETH2
};
